### ISSUE TITLE
[BUG] `UnicodeDecodeError: 'ascii' codec can't decode` when using `detect`

### ISSUE THREAD

**Issue by andrewvaughanj** [Ousret/charset_normalizer#153]
**Describe the bug**

I think this is likely to be very close to #136, but where I'm using `detect` instead of `safe_open`.

**To Reproduce**

Here's the code:

```python
from charset_normalizer import detect

import sys

fname = sys.argv[1]
encoding = detect(open(fname, "rb").read())["encoding"]

print(encoding)
```

and I have one "master" input (with is the translation unit of a large C++ program):

```
(venv) atg@vapvdatg01:/tmp> file=original.in && du -hs $file && wc $file && file $file
9.9M    original.in
  215429   907184 10372250 original.in
original.in: ASCII text, with very long lines (2253)
```

but I can use https://github.com/jleffler/scc-snapshots to make two further files:

```
(venv) atg@vapvdatg01:/tmp> file=comments_only.in && du -hs $file && wc $file && file $file
5.4M    comments_only.in
  93821  509098 5572212 comments_only.in
comments_only.in: ASCII text
```

and

```
(venv) atg@vapvdatg01:/tmp> file=no_comments.in && du -hs $file && wc $file && file $file
4.7M    no_comments.in
 188307  398128 4891407 no_comments.in
no_comments.in: ASCII text, with very long lines (2253)
```

If I try to use `detect` on either of `comments_only.in` or `no_comments.in`, then:

```
(venv) atg@vapvdatg01:/tmp> python3 test.py comments_only.in
utf-8
(venv) atg@vapvdatg01:/tmp> python3 test.py no_comments.in
ascii
```

However:

```
(venv) atg@vapvdatg01:/tmp> python3 test.py original.in
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    encoding = detect(open(fname, "rb").read())["encoding"]
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/legacy.py", line 28, in detect
    r = from_bytes(byte_str).best()
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/api.py", line 452, in from_bytes
    and fallback_u8.fingerprint != fallback_ascii.fingerprint
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/models.py", line 274, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/models.py", line 265, in output
    self._output_payload = str(self).encode(encoding, "replace")
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/models.py", line 114, in __str__
    self._string = str(self._payload, self._encoding, "strict")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 3026167: ordinal not in range(128)
```

and:

```
(venv) atg@vapvdatg01:/tmp> cat no_comments.in comments_only.in > merge.in && python3 test.py merge.in
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    encoding = detect(open(fname, "rb").read())["encoding"]
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/legacy.py", line 28, in detect
    r = from_bytes(byte_str).best()
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/api.py", line 452, in from_bytes
    and fallback_u8.fingerprint != fallback_ascii.fingerprint
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/models.py", line 274, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/models.py", line 265, in output
    self._output_payload = str(self).encode(encoding, "replace")
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/models.py", line 114, in __str__
    self._string = str(self._payload, self._encoding, "strict")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 6450930: ordinal not in range(128)
```

**Expected behavior**

Not to crash

**Logs**

This is the end of the traceback:

```
  File "test.py", line 6, in <module>
    encoding = detect(open(fname, "rb").read())["encoding"]
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/legacy.py", line 28, in detect
    r = from_bytes(byte_str).best()
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/api.py", line 452, in from_bytes
    and fallback_u8.fingerprint != fallback_ascii.fingerprint
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/models.py", line 274, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/models.py", line 265, in output
    self._output_payload = str(self).encode(encoding, "replace")
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/models.py", line 114, in __str__
    self._string = str(self._payload, self._encoding, "strict")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 6450930: ordinal not in range(128)
```

**Desktop (please complete the following information):**
 - OS: Linux 
 - Python version: 3.8.12
 - Package version: 2.0.10.dev0

**Additional context**

**Comment by andrewvaughanj** [comment]
Could be related to file size again:

```
(venv) atg@vapvdatg01:/tmp> size=10057858 && tail -c $size original.in > v2 && python test.py v2
MacCyrillic
(venv) atg@vapvdatg01:/tmp> size=10057859 && tail -c $size original.in > v2 && python test.py v2
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    encoding = detect(open(fname, "rb").read())["encoding"]
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/legacy.py", line 28, in detect
    r = from_bytes(byte_str).best()
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/api.py", line 452, in from_bytes
    and fallback_u8.fingerprint != fallback_ascii.fingerprint
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/models.py", line 274, in fingerprint
    return sha256(self.output()).hexdigest()
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/models.py", line 265, in output
    self._output_payload = str(self).encode(encoding, "replace")
  File "/tmp/venv/lib64/python3.8/site-packages/charset_normalizer/models.py", line 114, in __str__
    self._string = str(self._payload, self._encoding, "strict")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 2711776: ordinal not in range(128)
```

**Comment by Ousret** [comment]
Feel free to give feedback on that matter.

**Comment by andrewvaughanj** [comment]
> Feel free to give feedback on that matter.

Tested! Works great! Thanks, @Ousret!

**Comment by JensTimmerman** [comment]
I had the same issue, this patch also fixes it for me.
