### ISSUE TITLE
Uncaught Python exception: FileNotFoundError

### ISSUE THREAD

**Issue by OrianeK** [Ousret/charset_normalizer#178]
Hi,
I am a high school student just starting to learn about testing techniques. I found a bug in the latest version (2.0.12) of charset_normalizer while doing some fuzzing using the fuzzing tool Atheris. The reproducing process is shown below:
```
from charset_normalizer import normalize
normalize("")

```
Is raising `FileNotFoundError `with a traceback:

```
Details
Traceback (most recent call last):
  File "fuzzer_charset-normalizer.py", line 9, in TestOneInput
    normalize(data)
  File "/home/clou5/.local/lib/python3.8/site-packages/charset_normalizer/api.py", line 579, in normalize
    results = from_path(
  File "/home/clou5/.local/lib/python3.8/site-packages/charset_normalizer/api.py", line 554, in from_path
    with open(path, "rb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: b''
```
My environment
```
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import charset_normalizer
>>> print(charset_normalizer.__version__)
2.0.12
>>> 
```

**Comment by Ousret** [comment]
You did not read the documentation. https://charset-normalizer.readthedocs.io/en/latest/api.html
The `normalize` function takes a `PathLike` argument.
