### ISSUE TITLE
Latest release breaks PyInstaller-packaged code

### ISSUE THREAD

**Issue by itamarst** [Ousret/charset_normalizer#253]
**Describe the bug**
When packaging with PyInstaller, the resulting binary has issues due to a missing file.

Happens cross-platform (Windows, Linux, macOS). Python 3.9, Python 3.10.

```
Traceback (most recent call last):
  File "requests\compat.py", line 11, in <module>
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tahoe.py", line 19, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "allmydata\scripts\runner.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "allmydata\scripts\tahoe_invite.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "allmydata\client.py", line 32, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "allmydata\storage_client.py", line 77, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "allmydata\storage\http_client.py", line 32, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "treq\__init__.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "treq\api.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "treq\client.py", line 32, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "treq\response.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "requests\__init__.py", line 45, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "requests\exceptions.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "requests\compat.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "charset_normalizer\__init__.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "charset_normalizer\api.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "charset_normalizer\cd.py", line 9, in <module>
ModuleNotFoundError: No module named 'charset_normalizer.md__mypyc'
[7016] Failed to execute script 'tahoe' due to unhandled exception!
```

Another example: https://github.com/pyinstaller/pyinstaller/issues/7372

Insofar as there are other tools similar to PyInstaller (py2exe etc.) who might have similar issues, seems like maybe fixing it in charset_normalizer is the thing to do.

**Comment by Ousret** [comment]
Hi,

This is not an issue with charset-normalizer. I understand the frustration, but it is not in my power to resolve this.
A quick research is enough to see that PyInstaller is unwilling to include binaries in the resulting executable or archive.

- https://github.com/pyinstaller/pyinstaller/discussions/7220
- https://stackoverflow.com/questions/74182807/no-module-named-charset-normalizer-md-mypyc

Amongst other results. You'll need to tell PyInstaller to include it... (`--collect-all charset_normalizer`) or install the non-specific whl manually.

Regards,

**Comment by bwoodsend** [comment]
The problem isn't in including binaries - rather it's that `md__mypyc` is only ever imported in the cythonized `md` submodule which PyInstaller can't read. Just sticking a `from . import md__mypyc` anywhere in a `.py` file where PyInstaller can see it would solve this.

**Comment by Ousret** [comment]
OK. I used PyInstaller many times, including what it « cannot see » never was a problem… 
Nonetheless it has nothing to do with this project.

**Comment by kdeldycke** [comment]
For the record, this issue is not PyInstaller-specific, as it is also affecting Nuitka: https://github.com/Nuitka/Nuitka/issues/2020

**Comment by seanbudd** [comment]
Does anyone know how to fix this for py2exe?
It is suggested that is possible in the FAQ.
It seems that a future version of py2exe will hook this automatically, but in the meantime a manual hook would be great.

https://github.com/py2exe/py2exe/commit/7b34f06486fbc07500e323796d3f3d5fb862aee3

https://github.com/Ousret/charset_normalizer/blob/master/docs/community/faq.rst
>If your bundler program support it, set up a hook that implicitly import the hidden module. Otherwise, follow the guide on how to install the vanilla version of this package. (Section: Optional speedup extension)

**Comment by darthwalsh** [comment]
Thanks @Ousret for explaining that the problem isn't in charset-normalizer!

---

For anybody looking for a pyinstaller workaround, another option is to specify the hidden import: 

Pass the pyinstaller CLI flag: `--hidden-import charset_normalizer.md__mypyc`

Or, if using SPEC file, set the `hiddenimports` param passed to `Analysis`:

```python
     a = Analysis(['minimal.py'],
         pathex=['/Developer/PItests/minimal'],
         binaries=None,
         datas=None,
         hiddenimports=["charset_normalizer.md__mypyc"],
         hookspath=None,
         runtime_hooks=None,
         excludes=None,
         cipher=block_cipher)
```

**Comment by Johnserf-Seed** [comment]
Just now, I received a solution from GPT. Here's the packaging command I used, where I added the ```--hidden-import``` option to explicitly specify ```charset_normalizer.md__mypyc```:

```pyinstaller -F -i logo.ico --version-file API\TikTokTool.txt --hidden-import=charset_normalizer.md__mypyc TikTokTool.py```

This tells PyInstaller that charset_normalizer.md__mypyc is a hidden import that needs to be included in the packaged application. The result is that the program runs perfectly. The issue originally stemmed from an error reported in aiohttp within my project.


I hope this can help more people who encounter the same problem. 😀

**Comment by RhetTbull** [comment]
For anyone stumbling upon this and trying to get [py2app](https://pypi.org/project/py2app/) working, the answer is to include `charset_normalizer.md__mypyc` in your `includes` in py2app options.

Example from a [rumps](https://github.com/jaredks/rumps) app:

```python
OPTIONS = {
    "iconfile": "icon.icns",
    "plist": {
        "LSUIElement": True,
    },
    "packages": ["rumps"],
    "includes": ["charset_normalizer.md__mypyc"],
}

setup(
    app=APP,
    name="MyApp",
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
```
