### ISSUE TITLE
3.1.0 pip release seems broken

### ISSUE THREAD

**Issue by ani0075saha** [Ousret/charset_normalizer#278]
**Describe the bug**
Cannot import charset_normalizer

**To Reproduce**
import charset_normalizer

**Expected behavior**
Successful import

**Logs**
>>> import charset_normalizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/charset_normalizer/__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "/<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/charset_normalizer/api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
  File "charset_normalizer/md.py", line 5, in <module>
ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (<redacted>/anaconda3/envs/huggingface-bug-test/lib/python3.9/site-packages/charset_normalizer/constant.py)

**Desktop (please complete the following information):**
 - OS: Linux
 - Python version 3.9.16
 - Package version 3.1.0

**Additional context**
Imports causing issues in other libraries.
https://github.com/huggingface/transformers/issues/21858#issuecomment-1480094049

**Comment by Ousret** [comment]
I cannot reproduce—insufficient information.
It is most likely a problem within your environment.

- The title speaks of `pip` but the given stack trace shows evidence of `anaconda3`.
- I tried to set up environments based on conda v4 / anaconda3 and no exception occurred at import.
- Tested on Linux with the exact same criteria.

If there is no reproducibility on my end, I consider it external.
So, in case of clear evidence that this package is causing (directly) that exception, I am willing to fix it (and reopen that issue). But I doubt it has anything to do with that.

p.s. I don't maintain the conda package `charset-normalizer` if anything happens to be there.

**Comment by ani0075saha** [comment]
> I cannot reproduce—insufficient information. It is most likely a problem within your environment.
> 
> * The title speaks of `pip` but the given stack trace shows evidence of `anaconda3`.
> * I tried to set up environments based on conda v4 / anaconda3 and no exception occurred at import.
> * Tested on Linux with the exact same criteria.
> 
> If there is no reproducibility on my end, I consider it external. So, in case of clear evidence that this package is causing (directly) that exception, I am willing to fix it (and reopen that issue). But I doubt it has anything to do with that.
> 
> p.s. I don't maintain the conda package `charset-normalizer` if anything happens to be there.

```code
# packages in environment at /cmlscratch/anisaha1/anaconda3/envs/huggingface-bug-test:                                                                                                                           
#                                                                                                                                                                                                                
# Name                    Version                   Build  Channel                                                                                                                                               
_libgcc_mutex             0.1                        main                                                                                                                                                        
_openmp_mutex             5.1                       1_gnu                                                                                                                                                        
blas                      1.0                         mkl                                                                                                                                                        
brotlipy                  0.7.0           py39h27cfd23_1003                                                                                                                                                      
bzip2                     1.0.8                h7b6447c_0                                                                                                                                                        
ca-certificates           2023.01.10           h06a4308_0                                                                                                                                                        
certifi                   2022.12.7        py39h06a4308_0                                                                                                                                                        
cffi                      1.15.1           py39h5eee18b_3                                                                                                                                                        
charset-normalizer        3.1.0                    pypi_0    pypi                                                                                                                                                
cryptography              39.0.1           py39h9ce1e76_0                                                                                                                                                        
cuda-cudart               11.7.99                       0    nvidia                                                                                                                                              
cuda-cupti                11.7.101                      0    nvidia                                                                                                                                              
cuda-libraries            11.7.1                        0    nvidia                                                                                                                                              
cuda-nvrtc                11.7.99                       0    nvidia                                                                                                                                              
cuda-nvtx                 11.7.91                       0    nvidia                                                                                                                                              
cuda-runtime              11.7.1                        0    nvidia                                                                                                                                              
ffmpeg                    4.3                  hf484d3e_0    pytorch                                                                                                                                             
filelock                  3.10.0                   pypi_0    pypi                                                                                                                                                
flit-core                 3.6.0              pyhd3eb1b0_0                                                                                                                                                        
freetype                  2.12.1               h4a9f257_0                                                                                                                                                        
giflib                    5.2.1                h5eee18b_3                                                                                                                                                        
gmp                       6.2.1                h295c915_3                                                                                                                                                        
gnutls                    3.6.15               he1e5248_0                                                                                                                                                        
huggingface-hub           0.13.3                   pypi_0    pypi                                                                                                                                                
idna                      3.4              py39h06a4308_0                                                                                                                                                        
intel-openmp              2021.4.0          h06a4308_3561                                                                                                                                                        
jpeg                      9e                   h5eee18b_1                                                                                                                                                        
lame                      3.100                h7b6447c_0                                                                                                                                                        
lcms2                     2.12                 h3be6417_0                                                                                                                                                        
ld_impl_linux-64          2.38                 h1181459_1                                                                                                                                                        
lerc                      3.0                  h295c915_0                                                                                                                                                        
libcublas                 11.10.3.66                    0    nvidia                                                                                                                                              
libcufft                  10.7.2.124           h4fbf590_0    nvidia                                                                                                                                              
libcufile                 1.6.0.25                      0    nvidia                                                                                                                                              
libcurand                 10.3.2.56                     0    nvidia                                                                                                                                              
libcusolver               11.4.0.1                      0    nvidia  
libcusparse               11.7.4.91                     0    nvidia                                                                                                                                       [17/59]
libdeflate                1.17                 h5eee18b_0  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.2                h7f8727e_0  
libnpp                    11.7.4.75                     0    nvidia
libnvjpeg                 11.8.0.2                      0    nvidia
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.5.0                h6a678d5_2  
libunistring              0.9.10               h27cfd23_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
lz4-c                     1.9.4                h6a678d5_0  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
numpy                     1.24.2                   pypi_0    pypi
numpy-base                1.23.5           py39h31eccc5_0  
openh264                  2.1.1                h4ff587b_0  
openssl                   1.1.1t               h7f8727e_0  
packaging                 23.0                     pypi_0    pypi
pillow                    9.4.0            py39h6a678d5_0  
pip                       23.0.1           py39h06a4308_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 23.0.0           py39h06a4308_0  
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.16               h7a1cb2a_2  
pytorch                   1.13.1          py3.9_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_3    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0  
regex                     2022.10.31               pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
setuptools                65.6.3           py39h06a4308_0 
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.1               h5eee18b_0  
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.13.2                   pypi_0    pypi
torchaudio                0.13.1               py39_cu117    pytorch
torchvision               0.14.1               py39_cu117    pytorch
tqdm                      4.65.0                   pypi_0    pypi
transformers              4.28.0.dev0              pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
typing_extensions         4.4.0            py39h06a4308_0  
tzdata                    2022g                h04d1e81_0  
urllib3                   1.26.15                  pypi_0    pypi
wheel                     0.38.4           py39h06a4308_0  
xz                        5.2.10               h5eee18b_1  
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.2                ha4553b6_0   
```

Yes, it's a conda environment but the charset_normalizer installation is from the pypi channel. Also, the error seems to emanate from a missing chardet dependency. Once I install chardet with ```code pip install chardet```, the problem gets solved.

So, do you think this is a dependency problem which needs to be fixed in charset_normalizer?

**Comment by Ousret** [comment]
re

It is not because of that package.
My guess is that using pip in conda environment makes some confusion.

Yes, you have 3.1.0 installed, but for some reason, it is trying to import `charset_normalizer.constant` from the v2.0.4 (conda original depo) which does not have the constant `COMMON_SAFE_ASCII_CHARACTERS` in it.

You have literally a Frankenstein environment.

**Comment by Khoa-NT** [comment]
@Ousret you are right.

I installed `charset-normalizer` with [conda](https://anaconda.org/conda-forge/charset-normalizer) 
`conda install conda-forge::charset-normalizer`

and the problem was gone.
